theme: jekyll-theme-minimal
logo: /image/profile.png
description: "Fudan University · <a href='https://baolab-fudan.github.io/'>Bao Lab</a>"
title: Understand the principle behind complex systems
google_analytics: UA-102911962-1
